import React from 'react'
import { Grid } from '@components'
import { WagIcon } from './Icon'

// For all of the icons I am going to display for the Walgreens Project

const icons = [
  { icon: 'device--desktop' },
  { icon: 'device--tablet' },
  { icon: 'device--mobile' },
  { icon: 'device--watch' },
  { icon: 'device--kiosk' },
  { icon: 'camera' },
  { icon: 'device--usb' },
  { icon: 'image' },
  { icon: 'device--video' },
  { icon: 'link' },
  { icon: 'device--resize' },
  { icon: 'download' },
  { icon: 'upload' },
  { icon: 'folder' },
  { icon: 'folder--add' },
  { icon: 'folder--download' },
  { icon: 'clipboard' },
  { icon: 'print' },
  { icon: 'scan' },
  { icon: 'email' },
  { icon: 'trash' },
  { icon: 'share' },
  { icon: 'edit' },
  { icon: 'edit--v2' },
  { icon: 'crop' },
  { icon: 'rotate' },
  { icon: 'minimize' },
  { icon: 'filter' },
  { icon: 'graph' },
  { icon: 'list' },
  { icon: 'funnel' },
  { icon: 'brightness' },
  { icon: 'auto-enhance' },
  { icon: 'settings' },
  { icon: 'search' },
  { icon: 'zoom' },
  { icon: 'albums' },
  { icon: 'prints' },
  { icon: 'prints--checked' },
  { icon: 'content' },
  { icon: 'content--v2' },
  { icon: 'pin' },
  { icon: 'location' },
  { icon: 'eye' },
  { icon: 'contacts' },
  { icon: 'glasses' },
  { icon: 'tooth' },
  { icon: 'hearing' },
  { icon: 'inhaler' },
  { icon: 'health--scale' },
  { icon: 'apple' },
  { icon: 'health--sleep' },
  { icon: 'cal' },
  { icon: 'cal--week' },
  { icon: 'cal--year' },
  { icon: 'cal--year-half' },
  { icon: 'clock' },
  { icon: 'clock--sameday' },
  { icon: 'clock--reorder' },
  { icon: 'clock--24hr' },
  { icon: 'ship' },
  { icon: 'ship--reorder' },
  { icon: 'ship--sameday' },
  { icon: 'ship--truck' },
  { icon: 'car' },
  { icon: 'store' },
  { icon: 'bag' },
  { icon: 'cart' },
  { icon: 'cart--add' },
  { icon: 'cart--added' },
  { icon: 'credit--card' },
  { icon: 'insurance' },
  { icon: 'star' },
  { icon: 'reward' },
  { icon: 'trophy' },
  { icon: 'present' },
  { icon: 'coupon' },
  { icon: 'coupon--clip' },
  { icon: 'heart' },
  { icon: 'heart--info' },
  { icon: 'heart--rate' },
  { icon: 'health--vitals' },
  { icon: 'health--dashboard' },
  { icon: 'monitoring' },
  { icon: 'blood' },
  { icon: 'blood--glucose' },
  { icon: 'flushot' },
  { icon: 'flushot--cal' },
  { icon: 'bandaid' },
  { icon: 'rx--health' },
  { icon: 'stop-smoking' },
  { icon: 'otc' },
  { icon: 'rx' },
  { icon: 'rx--refill' },
  { icon: 'rx--clock' },
  { icon: 'rx--side-effects' },
  { icon: 'rx--alt' },
  { icon: 'rx--ready' },
  { icon: 'rx--express' },
  { icon: 'rx--refill-v2' },
  { icon: 'rx--transfer' },
  { icon: 'rx--info' },
  { icon: 'rx--pad' },
  { icon: 'rx--mobile' },
  { icon: 'avatar' },
  { icon: 'avatar--alt' },
  { icon: 'dr' },
  { icon: 'pharm' },
  { icon: 'privacy' },
  { icon: 'family' },
  { icon: 'community' },
  { icon: 'running' },
  { icon: 'walking' },
  { icon: 'stretching' },
  { icon: 'accessibility' },
  { icon: 'cycling' },
  { icon: 'standing' },
  { icon: 'chat' },
  { icon: 'chat--typing' },
  { icon: 'chat--v2' },
  { icon: 'chat--rx' },
  { icon: 'price' },
  { icon: 'question' },
  { icon: 'alert' },
  { icon: 'info' },
  { icon: 'check' },
  { icon: 'add' },
  { icon: 'minus' },
  { icon: 'close' },
  { icon: 'disabled' }
]

// ---------- This is the end of declarations ---------- //

export const WalgreensIcons = () => {
  return(

    <Grid 
      columns={ 14 } 
      largeDesktopColumns={ 12 } 
      smallDesktopColumns={ 8 }
      tabletColumns={ 5 }
      mobileColumns={ 4 }
    >
      { icons.map(( icon, i ) => (
        <WagIcon key={`icon-${ i }`} icon={ icon.icon } />
      ))}
    </Grid>

  )
}
