export { StaticHeader } from './Header/Header'
export { StaticNav } from './Nav/Nav'
export { Status } from './Status/Status'
export { Contacts } from './Contacts/Contacts'
export { Profile } from './Profile/Profile'
export { Help } from './Help/Help'